version: '3.7'

services:
  firstrun:
    container_name: firstrun
    privileged: true
    image: docker:dind
    restart: "no"
    environment:
      - LND_PATH=${PWD}
    volumes:
      - ./lnd:/lnd
      - ./tor/etc/tor/torrc:/etc/tor/torrc:rw
      - ./firstrun.sh:/firstrun.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "cd / && sh /firstrun.sh"
    
  tor:
    container_name: watchtower_tor
    image: lncm/tor:0.4.7.13@sha256:5a3cfb478d978feb1426ce6dca8e10906bbdd72cff94d7c0c589339f717b2503
    user: toruser
    restart: unless-stopped
    volumes:
      - ./tor/etc/tor/torrc:/etc/tor/torrc:ro
      - ./tor/data:/var/lib/tor/
    depends_on:
      firstrun:
        condition: service_completed_successfully
    networks:
      default:
        ipv4_address: 172.0.0.2
    environment:
      HOME: /var/lib/tor/
  lnd:
    container_name: watchtower
    image: lightninglabs/lnd:v0.16.0-beta
    user: 1000:1000
    depends_on:
      firstrun:
        condition: service_completed_successfully
      tor:
        condition: service_started
    volumes:
      - ./lnd:/data/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.0.0.3

networks:
  default:
    name: watchtower_network
    ipam:
      driver: default
      config:
        - subnet: "172.0.0.0/24"
