version: '3.7'

services:
  firstrun:
    container_name: firstrun
    privileged: true
    image: docker:dind
    restart: "no"
    volumes:
      - ./lnd:/lnd
      - ./tor/torrc-lnd:/tor/torrc-lnd
      - ./firstrun.sh:/firstrun.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "cd / && sh /firstrun.sh"
    networks:
      - default
  tor:
    container_name: watchtower_tor
    image: lncm/tor:0.4.7.9
    user: toruser
    restart: on-failure
    volumes:
      - ./tor/torrc-lnd:/etc/tor/torrc:ro
      - ./tor/data:/var/lib/tor/
    depends_on:
      firstrun:
        condition: service_completed_successfully
    networks:
      default:
        ipv4_address: 172.0.0.2
  lnd:
    container_name: watchtower
    image: lightninglabs/lnd:v0.15.4-beta
    user: 1000:1000
    depends_on:
      firstrun:
        condition: service_completed_successfully
      tor:
        condition: service_started
    volumes:
      - ./lnd:/data/.lnd
    environment:
      HOME: /data
    restart: on-failure
    ports:
      - 9911:9911
    networks:
      default:
        ipv4_address: 172.0.0.3

networks:
  default:
    name: watchtower_network
    ipam:
      driver: default
      config:
        - subnet: "172.0.0.0/24"
