version: '3.7'

services:
  tor:
    container_name: watchtower_tor
    image: lncm/tor:0.4.7.9
    user: toruser
    restart: on-failure
    volumes:
      - ${PWD}/tor/torrc-lnd:/etc/tor/torrc
      - ${PWD}/tor/data:/var/lib/tor/
    networks:
      default:
        ipv4_address: 172.0.0.2
  lnd:
    container_name: watchtower
    image: lightninglabs/lnd:v0.15.4-beta
    user: 1000:1000
    depends_on:
      - tor
    volumes:
      - ${PWD}/lnd:/data/.lnd
    environment:
      HOME: /data
    restart: on-failure
    ports:
      - 9911:9911
    networks:
      default:
        ipv4_address: 172.0.0.3

networks:
  default:
    name: watchtower_network
    ipam:
      driver: default
      config:
        - subnet: "172.0.0.0/24"
